# POST http://127.0.0.1:3000/user/register HTTP/1.1
# content-type: application/json

# {
#   "username": "wuyupei",
#   "nickName": "super_wuyupei",
#   "password": "123456",
#   "email": "495174699@qq.com",
#   "captcha": "207624"
# }

# GET http://127.0.0.1:3000/user/register-captcha?address=495174699@qq.com HTTP/1.1
# content-type: application/json


# GET http://127.0.0.1:3000/user/initData HTTP/1.1
# content-type: application/json


# POST http://127.0.0.1:3000/api/user/admin/login HTTP/1.1
# content-type: application/json

# {
#   "username": "wuyupei",
#   "password": "111111"
# }


POST http://127.0.0.1:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "username": "zhangsan",
  "password": "222222"
}
